inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_from:
  - .rubocop_rspec.yml

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "spec/fixtures/**/*"
    - ".gem/ruby/3.2.1/gems/**/*"
